# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v7.1.1
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.io_k8s_apimachinery_pkg_apis_meta_v1_initializers import IoK8sApimachineryPkgApisMetaV1Initializers


class TestIoK8sApimachineryPkgApisMetaV1Initializers(unittest.TestCase):
    """ IoK8sApimachineryPkgApisMetaV1Initializers unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1Initializers(self):
        """
        Test IoK8sApimachineryPkgApisMetaV1Initializers
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.io_k8s_apimachinery_pkg_apis_meta_v1_initializers.IoK8sApimachineryPkgApisMetaV1Initializers()
        pass


if __name__ == '__main__':
    unittest.main()
