# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v7.1.1
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.io_k8s_apimachinery_pkg_runtime_raw_extension import IoK8sApimachineryPkgRuntimeRawExtension


class TestIoK8sApimachineryPkgRuntimeRawExtension(unittest.TestCase):
    """ IoK8sApimachineryPkgRuntimeRawExtension unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgRuntimeRawExtension(self):
        """
        Test IoK8sApimachineryPkgRuntimeRawExtension
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.io_k8s_apimachinery_pkg_runtime_raw_extension.IoK8sApimachineryPkgRuntimeRawExtension()
        pass


if __name__ == '__main__':
    unittest.main()
