# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v7.1.1
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.io_k8s_api_core_v1_node_affinity import IoK8sApiCoreV1NodeAffinity


class TestIoK8sApiCoreV1NodeAffinity(unittest.TestCase):
    """ IoK8sApiCoreV1NodeAffinity unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1NodeAffinity(self):
        """
        Test IoK8sApiCoreV1NodeAffinity
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.io_k8s_api_core_v1_node_affinity.IoK8sApiCoreV1NodeAffinity()
        pass


if __name__ == '__main__':
    unittest.main()
