# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v7.1.1
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubernetes.client
from kubernetes.client.rest import ApiException
from kubernetes.client.models.v1beta1_frontend_rule import V1beta1FrontendRule


class TestV1beta1FrontendRule(unittest.TestCase):
    """ V1beta1FrontendRule unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1FrontendRule(self):
        """
        Test V1beta1FrontendRule
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubernetes.client.models.v1beta1_frontend_rule.V1beta1FrontendRule()
        pass


if __name__ == '__main__':
    unittest.main()
